GAME_SERVER_SRC_DIR=../game/server
GAME_SERVER_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server
GAME_SERVER___COMMON_SRC_DIR=../game/server/../../common
GAME_SERVER___COMMON_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/common
GAME_SERVER___PUBLIC_SRC_DIR=../game/server/../../public
GAME_SERVER___PUBLIC_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/public
GAME_SERVER___PUBLIC_KEYFRAME_SRC_DIR=../game/server/../../public/keyframe
GAME_SERVER___PUBLIC_KEYFRAME_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/public/keyframe
GAME_SERVER___PUBLIC_TIER0_SRC_DIR=../game/server/../../public/tier0
GAME_SERVER___PUBLIC_TIER0_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/public/tier0
GAME_SERVER__SHARED_SRC_DIR=../game/server/../shared
GAME_SERVER__SHARED_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/shared
GAME_SERVER__SHARED_HL2_SRC_DIR=../game/server/../shared/hl2
GAME_SERVER__SHARED_HL2_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/shared/hl2
GAME_SERVER__SHARED_HL2MP_SRC_DIR=../game/server/../shared/hl2mp
GAME_SERVER__SHARED_HL2MP_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/shared/hl2mp
GAME_SERVER__SHARED_MULTIPLAYER_SRC_DIR=../game/server/../shared/Multiplayer
GAME_SERVER__SHARED_MULTIPLAYER_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/shared/Multiplayer
GAME_SERVER_HL2_SRC_DIR=../game/server/hl2
GAME_SERVER_HL2_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/hl2
GAME_SERVER_HL2MP_SRC_DIR=../game/server/hl2mp
GAME_SERVER_HL2MP_OBJ_DIR=obj/$(NAME)_$(ARCH)/game/server/hl2mp


INCLUDES=-I../game/server/../../common -I../game/server/../../public -I../game/server/../../public/tier0 -I../game/server/../../public/tier1 -I../game/server/. -I../game/server/../../game/shared -I../game/server/../../utils/common -I../game/server/../../game/shared/hl2 -I../game/server/./hl2 -I../game/server/./hl2mp -I../game/server/../../game/shared/hl2mp -I../game/server/../../game/shared/Multiplayer -DNDEBUG -D_USRDLL -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DGAME_DLL -DVECTOR -DPROTECTED_THINGS_ENABLE -Dfopen=dont_use_fopen -Dsprintf=use_Q_snprintf_instead_of_sprintf -Dstrncpy=use_Q_strncpy_instead -D_snprintf=use_Q_snprintf_instead -DHL2MP -DMP_SDK -DHL2_DLL -DVERSION_SAFE_STEAM_API_INTERFACES 

GAME_SERVER_OBJS= \
	$(GAME_SERVER_OBJ_DIR)/ai_activity.o \
	$(GAME_SERVER_OBJ_DIR)/ai_baseactor.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basehumanoid.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc_flyer.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc_flyer_new.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc_movement.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc_physicsflyer.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc_schedule.o \
	$(GAME_SERVER_OBJ_DIR)/ai_basenpc_squad.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior_assault.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior_fear.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior_follow.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior_lead.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior_rappel.o \
	$(GAME_SERVER_OBJ_DIR)/ai_behavior_standoff.o \
	$(GAME_SERVER_OBJ_DIR)/ai_blended_movement.o \
	$(GAME_SERVER_OBJ_DIR)/ai_concommands.o \
	$(GAME_SERVER_OBJ_DIR)/ai_condition.o \
	$(GAME_SERVER_OBJ_DIR)/AI_Criteria.o \
	$(GAME_SERVER_OBJ_DIR)/ai_default.o \
	$(GAME_SERVER_OBJ_DIR)/ai_dynamiclink.o \
	$(GAME_SERVER_OBJ_DIR)/ai_event.o \
	$(GAME_SERVER_OBJ_DIR)/ai_goalentity.o \
	$(GAME_SERVER_OBJ_DIR)/ai_hint.o \
	$(GAME_SERVER_OBJ_DIR)/ai_hull.o \
	$(GAME_SERVER_OBJ_DIR)/ai_initutils.o \
	$(GAME_SERVER_OBJ_DIR)/AI_Interest_Target.o \
	$(GAME_SERVER_OBJ_DIR)/ai_link.o \
	$(GAME_SERVER_OBJ_DIR)/ai_localnavigator.o \
	$(GAME_SERVER_OBJ_DIR)/ai_looktarget.o \
	$(GAME_SERVER_OBJ_DIR)/ai_memory.o \
	$(GAME_SERVER_OBJ_DIR)/ai_motor.o \
	$(GAME_SERVER_OBJ_DIR)/ai_moveprobe.o \
	$(GAME_SERVER_OBJ_DIR)/ai_moveshoot.o \
	$(GAME_SERVER_OBJ_DIR)/ai_movesolver.o \
	$(GAME_SERVER_OBJ_DIR)/ai_namespaces.o \
	$(GAME_SERVER_OBJ_DIR)/ai_navigator.o \
	$(GAME_SERVER_OBJ_DIR)/ai_network.o \
	$(GAME_SERVER_OBJ_DIR)/ai_networkmanager.o \
	$(GAME_SERVER_OBJ_DIR)/ai_node.o \
	$(GAME_SERVER_OBJ_DIR)/ai_pathfinder.o \
	$(GAME_SERVER_OBJ_DIR)/ai_planesolver.o \
	$(GAME_SERVER_OBJ_DIR)/ai_playerally.o \
	$(GAME_SERVER_OBJ_DIR)/ai_relationship.o \
	$(GAME_SERVER_OBJ_DIR)/AI_ResponseSystem.o \
	$(GAME_SERVER_OBJ_DIR)/ai_route.o \
	$(GAME_SERVER_OBJ_DIR)/ai_saverestore.o \
	$(GAME_SERVER_OBJ_DIR)/ai_schedule.o \
	$(GAME_SERVER_OBJ_DIR)/ai_scriptconditions.o \
	$(GAME_SERVER_OBJ_DIR)/ai_senses.o \
	$(GAME_SERVER_OBJ_DIR)/ai_sentence.o \
	$(GAME_SERVER_OBJ_DIR)/ai_speech.o \
	$(GAME_SERVER_OBJ_DIR)/ai_speechfilter.o \
	$(GAME_SERVER_OBJ_DIR)/ai_squad.o \
	$(GAME_SERVER_OBJ_DIR)/ai_squadslot.o \
	$(GAME_SERVER_OBJ_DIR)/ai_tacticalservices.o \
	$(GAME_SERVER_OBJ_DIR)/ai_task.o \
	$(GAME_SERVER_OBJ_DIR)/ai_trackpather.o \
	$(GAME_SERVER_OBJ_DIR)/ai_utils.o \
	$(GAME_SERVER_OBJ_DIR)/ai_waypoint.o \
	$(GAME_SERVER_OBJ_DIR)/base_transmit_proxy.o \
	$(GAME_SERVER_OBJ_DIR)/baseanimating.o \
	$(GAME_SERVER_OBJ_DIR)/BaseAnimatingOverlay.o \
	$(GAME_SERVER_OBJ_DIR)/basecombatcharacter.o \
	$(GAME_SERVER_OBJ_DIR)/basecombatweapon.o \
	$(GAME_SERVER_OBJ_DIR)/baseentity.o \
	$(GAME_SERVER_OBJ_DIR)/baseflex.o \
	$(GAME_SERVER_OBJ_DIR)/basegrenade_concussion.o \
	$(GAME_SERVER_OBJ_DIR)/basegrenade_contact.o \
	$(GAME_SERVER_OBJ_DIR)/basegrenade_timed.o \
	$(GAME_SERVER_OBJ_DIR)/basemultiplayerplayer.o \
	$(GAME_SERVER_OBJ_DIR)/baseviewmodel.o \
	$(GAME_SERVER_OBJ_DIR)/bitstring.o \
	$(GAME_SERVER_OBJ_DIR)/bmodels.o \
	$(GAME_SERVER_OBJ_DIR)/bp_random.o \
	$(GAME_SERVER_OBJ_DIR)/buttons.o \
	$(GAME_SERVER_OBJ_DIR)/cbase.o \
	$(GAME_SERVER_OBJ_DIR)/client.o \
	$(GAME_SERVER_OBJ_DIR)/colorcorrection.o \
	$(GAME_SERVER_OBJ_DIR)/colorcorrectionvolume.o \
	$(GAME_SERVER_OBJ_DIR)/CommentarySystem.o \
	$(GAME_SERVER_OBJ_DIR)/controlentities.o \
	$(GAME_SERVER_OBJ_DIR)/cplane.o \
	$(GAME_SERVER_OBJ_DIR)/CRagdollMagnet.o \
	$(GAME_SERVER_OBJ_DIR)/damagemodifier.o \
	$(GAME_SERVER_OBJ_DIR)/doors.o \
	$(GAME_SERVER_OBJ_DIR)/dynamiclight.o \
	$(GAME_SERVER_OBJ_DIR)/effects.o \
	$(GAME_SERVER_OBJ_DIR)/EffectsServer.o \
	$(GAME_SERVER_OBJ_DIR)/entityblocker.o \
	$(GAME_SERVER_OBJ_DIR)/EntityDissolve.o \
	$(GAME_SERVER_OBJ_DIR)/EntityFlame.o \
	$(GAME_SERVER_OBJ_DIR)/entitylist.o \
	$(GAME_SERVER_OBJ_DIR)/EntityParticleTrail.o \
	$(GAME_SERVER_OBJ_DIR)/env_debughistory.o \
	$(GAME_SERVER_OBJ_DIR)/env_effectsscript.o \
	$(GAME_SERVER_OBJ_DIR)/env_entity_maker.o \
	$(GAME_SERVER_OBJ_DIR)/env_particlescript.o \
	$(GAME_SERVER_OBJ_DIR)/env_player_surface_trigger.o \
	$(GAME_SERVER_OBJ_DIR)/env_projectedtexture.o \
	$(GAME_SERVER_OBJ_DIR)/env_screenoverlay.o \
	$(GAME_SERVER_OBJ_DIR)/env_texturetoggle.o \
	$(GAME_SERVER_OBJ_DIR)/env_tonemap_controller.o \
	$(GAME_SERVER_OBJ_DIR)/env_zoom.o \
	$(GAME_SERVER_OBJ_DIR)/EnvBeam.o \
	$(GAME_SERVER_OBJ_DIR)/EnvFade.o \
	$(GAME_SERVER_OBJ_DIR)/EnvHudHint.o \
	$(GAME_SERVER_OBJ_DIR)/EnvLaser.o \
	$(GAME_SERVER_OBJ_DIR)/EnvMessage.o \
	$(GAME_SERVER_OBJ_DIR)/envmicrophone.o \
	$(GAME_SERVER_OBJ_DIR)/EnvShake.o \
	$(GAME_SERVER_OBJ_DIR)/EnvSpark.o \
	$(GAME_SERVER_OBJ_DIR)/EventLog.o \
	$(GAME_SERVER_OBJ_DIR)/explode.o \
	$(GAME_SERVER_OBJ_DIR)/filters.o \
	$(GAME_SERVER_OBJ_DIR)/fire.o \
	$(GAME_SERVER_OBJ_DIR)/fire_smoke.o \
	$(GAME_SERVER_OBJ_DIR)/fish.o \
	$(GAME_SERVER_OBJ_DIR)/fogcontroller.o \
	$(GAME_SERVER_OBJ_DIR)/fourwheelvehiclephysics.o \
	$(GAME_SERVER_OBJ_DIR)/func_areaportal.o \
	$(GAME_SERVER_OBJ_DIR)/func_areaportalbase.o \
	$(GAME_SERVER_OBJ_DIR)/func_areaportalwindow.o \
	$(GAME_SERVER_OBJ_DIR)/func_break.o \
	$(GAME_SERVER_OBJ_DIR)/func_breakablesurf.o \
	$(GAME_SERVER_OBJ_DIR)/func_dust.o \
	$(GAME_SERVER_OBJ_DIR)/func_gamepoints.o \
	$(GAME_SERVER_OBJ_DIR)/func_ladder_endpoint.o \
	$(GAME_SERVER_OBJ_DIR)/func_lod.o \
	$(GAME_SERVER_OBJ_DIR)/game_config.o \
	$(GAME_SERVER_OBJ_DIR)/game_entities.o \
	$(GAME_SERVER_OBJ_DIR)/func_movelinear.o \
	$(GAME_SERVER_OBJ_DIR)/func_occluder.o \
	$(GAME_SERVER_OBJ_DIR)/func_reflective_glass.o \
	$(GAME_SERVER_OBJ_DIR)/func_smokevolume.o \
	$(GAME_SERVER_OBJ_DIR)/game.o \
	$(GAME_SERVER_OBJ_DIR)/game_ui.o \
	$(GAME_SERVER_OBJ_DIR)/gamehandle.o \
	$(GAME_SERVER_OBJ_DIR)/gameinterface.o \
	$(GAME_SERVER_OBJ_DIR)/GameStats_BasicStatsFunctions.o \
	$(GAME_SERVER_OBJ_DIR)/gametrace_dll.o \
	$(GAME_SERVER_OBJ_DIR)/gameweaponmanager.o \
	$(GAME_SERVER_OBJ_DIR)/genericactor.o \
	$(GAME_SERVER_OBJ_DIR)/genericmonster.o \
	$(GAME_SERVER_OBJ_DIR)/gib.o \
	$(GAME_SERVER_OBJ_DIR)/globals.o \
	$(GAME_SERVER_OBJ_DIR)/globalstate.o \
	$(GAME_SERVER_OBJ_DIR)/grenadethrown.o \
	$(GAME_SERVER_OBJ_DIR)/guntarget.o \
	$(GAME_SERVER_OBJ_DIR)/h_ai.o \
	$(GAME_SERVER_OBJ_DIR)/h_cycler.o \
	$(GAME_SERVER_OBJ_DIR)/h_export.o \
	$(GAME_SERVER_OBJ_DIR)/hierarchy.o \
	$(GAME_SERVER_OBJ_DIR)/hltvdirector.o \
	$(GAME_SERVER_OBJ_DIR)/info_camera_link.o \
	$(GAME_SERVER_OBJ_DIR)/info_overlay_accessor.o \
	$(GAME_SERVER_OBJ_DIR)/init_factory.o \
	$(GAME_SERVER_OBJ_DIR)/intermission.o \
	$(GAME_SERVER_OBJ_DIR)/item_world.o \
	$(GAME_SERVER_OBJ_DIR)/lightglow.o \
	$(GAME_SERVER_OBJ_DIR)/lights.o \
	$(GAME_SERVER_OBJ_DIR)/logic_measure_movement.o \
	$(GAME_SERVER_OBJ_DIR)/logic_navigation.o \
	$(GAME_SERVER_OBJ_DIR)/logicauto.o \
	$(GAME_SERVER_OBJ_DIR)/logicentities.o \
	$(GAME_SERVER_OBJ_DIR)/logicrelay.o \
	$(GAME_SERVER_OBJ_DIR)/mapentities.o \
	$(GAME_SERVER_OBJ_DIR)/maprules.o \
	$(GAME_SERVER_OBJ_DIR)/MaterialModifyControl.o \
	$(GAME_SERVER_OBJ_DIR)/message_entity.o \
	$(GAME_SERVER_OBJ_DIR)/modelentities.o \
	$(GAME_SERVER_OBJ_DIR)/monstermaker.o \
	$(GAME_SERVER_OBJ_DIR)/movehelper_server.o \
	$(GAME_SERVER_OBJ_DIR)/movement.o \
	$(GAME_SERVER_OBJ_DIR)/mtrand.o \
	$(GAME_SERVER_OBJ_DIR)/nav_area.o \
	$(GAME_SERVER_OBJ_DIR)/nav_colors.o \
	$(GAME_SERVER_OBJ_DIR)/nav_edit.o \
	$(GAME_SERVER_OBJ_DIR)/nav_file.o \
	$(GAME_SERVER_OBJ_DIR)/nav_generate.o \
	$(GAME_SERVER_OBJ_DIR)/nav_ladder.o \
	$(GAME_SERVER_OBJ_DIR)/nav_mesh.o \
	$(GAME_SERVER_OBJ_DIR)/nav_node.o \
	$(GAME_SERVER_OBJ_DIR)/ndebugoverlay.o \
	$(GAME_SERVER_OBJ_DIR)/npc_vehicledriver.o \
	$(GAME_SERVER_OBJ_DIR)/particle_light.o \
	$(GAME_SERVER_OBJ_DIR)/particle_system.o \
	$(GAME_SERVER_OBJ_DIR)/pathcorner.o \
	$(GAME_SERVER_OBJ_DIR)/pathtrack.o \
	$(GAME_SERVER_OBJ_DIR)/phys_controller.o \
	$(GAME_SERVER_OBJ_DIR)/physconstraint.o \
	$(GAME_SERVER_OBJ_DIR)/physics.o \
	$(GAME_SERVER_OBJ_DIR)/physics_bone_follower.o \
	$(GAME_SERVER_OBJ_DIR)/physics_cannister.o \
	$(GAME_SERVER_OBJ_DIR)/physics_fx.o \
	$(GAME_SERVER_OBJ_DIR)/physics_impact_damage.o \
	$(GAME_SERVER_OBJ_DIR)/physics_main.o \
	$(GAME_SERVER_OBJ_DIR)/physics_npc_solver.o \
	$(GAME_SERVER_OBJ_DIR)/physics_prop_ragdoll.o \
	$(GAME_SERVER_OBJ_DIR)/physobj.o \
	$(GAME_SERVER_OBJ_DIR)/player.o \
	$(GAME_SERVER_OBJ_DIR)/player_command.o \
	$(GAME_SERVER_OBJ_DIR)/player_lagcompensation.o \
	$(GAME_SERVER_OBJ_DIR)/player_pickup.o \
	$(GAME_SERVER_OBJ_DIR)/player_resource.o \
	$(GAME_SERVER_OBJ_DIR)/playerlocaldata.o \
	$(GAME_SERVER_OBJ_DIR)/plugin_check.o \
	$(GAME_SERVER_OBJ_DIR)/point_camera.o \
	$(GAME_SERVER_OBJ_DIR)/point_devshot_camera.o \
	$(GAME_SERVER_OBJ_DIR)/point_playermoveconstraint.o \
	$(GAME_SERVER_OBJ_DIR)/point_spotlight.o \
	$(GAME_SERVER_OBJ_DIR)/point_template.o \
	$(GAME_SERVER_OBJ_DIR)/pointanglesensor.o \
	$(GAME_SERVER_OBJ_DIR)/PointAngularVelocitySensor.o \
	$(GAME_SERVER_OBJ_DIR)/pointhurt.o \
	$(GAME_SERVER_OBJ_DIR)/pointteleport.o \
	$(GAME_SERVER_OBJ_DIR)/props.o \
	$(GAME_SERVER_OBJ_DIR)/ragdoll_manager.o \
	$(GAME_SERVER_OBJ_DIR)/RagdollBoogie.o \
	$(GAME_SERVER_OBJ_DIR)/recipientfilter.o \
	$(GAME_SERVER_OBJ_DIR)/rope.o \
	$(GAME_SERVER_OBJ_DIR)/saverestore_gamedll.o \
	$(GAME_SERVER_OBJ_DIR)/sceneentity.o \
	$(GAME_SERVER_OBJ_DIR)/scratchpad_gamedll_helpers.o \
	$(GAME_SERVER_OBJ_DIR)/scripted.o \
	$(GAME_SERVER_OBJ_DIR)/scriptedtarget.o \
	$(GAME_SERVER_OBJ_DIR)/sendproxy.o \
	$(GAME_SERVER_OBJ_DIR)/serverbenchmark_base.o \
	$(GAME_SERVER_OBJ_DIR)/ServerNetworkProperty.o \
	$(GAME_SERVER_OBJ_DIR)/shadowcontrol.o \
	$(GAME_SERVER_OBJ_DIR)/SkyCamera.o \
	$(GAME_SERVER_OBJ_DIR)/slideshow_display.o \
	$(GAME_SERVER_OBJ_DIR)/sound.o \
	$(GAME_SERVER_OBJ_DIR)/soundent.o \
	$(GAME_SERVER_OBJ_DIR)/soundscape.o \
	$(GAME_SERVER_OBJ_DIR)/soundscape_system.o \
	$(GAME_SERVER_OBJ_DIR)/spotlightend.o \
	$(GAME_SERVER_OBJ_DIR)/sprite_perfmonitor.o \
	$(GAME_SERVER_OBJ_DIR)/subs.o \
	$(GAME_SERVER_OBJ_DIR)/sun.o \
	$(GAME_SERVER_OBJ_DIR)/tanktrain.o \
	$(GAME_SERVER_OBJ_DIR)/team.o \
	$(GAME_SERVER_OBJ_DIR)/team_spawnpoint.o \
	$(GAME_SERVER_OBJ_DIR)/TemplateEntities.o \
	$(GAME_SERVER_OBJ_DIR)/tempmonster.o \
	$(GAME_SERVER_OBJ_DIR)/tesla.o \
	$(GAME_SERVER_OBJ_DIR)/test_proxytoggle.o \
	$(GAME_SERVER_OBJ_DIR)/test_stressentities.o \
	$(GAME_SERVER_OBJ_DIR)/testfunctions.o \
	$(GAME_SERVER_OBJ_DIR)/testtraceline.o \
	$(GAME_SERVER_OBJ_DIR)/textstatsmgr.o \
	$(GAME_SERVER_OBJ_DIR)/timedeventmgr.o \
	$(GAME_SERVER_OBJ_DIR)/trains.o \
	$(GAME_SERVER_OBJ_DIR)/triggers.o \
	$(GAME_SERVER_OBJ_DIR)/trigger_voidfall.o \
	$(GAME_SERVER_OBJ_DIR)/util.o \
	$(GAME_SERVER_OBJ_DIR)/variant_t.o \
	$(GAME_SERVER_OBJ_DIR)/vehicle_base.o \
	$(GAME_SERVER_OBJ_DIR)/vehicle_baseserver.o \
	$(GAME_SERVER_OBJ_DIR)/vguiscreen.o \
	$(GAME_SERVER_OBJ_DIR)/waterbullet.o \
	$(GAME_SERVER_OBJ_DIR)/WaterLODControl.o \
	$(GAME_SERVER_OBJ_DIR)/wcedit.o \
	$(GAME_SERVER_OBJ_DIR)/weight_button.o \
	$(GAME_SERVER_OBJ_DIR)/world.o \
	$(GAME_SERVER_OBJ_DIR)/stdafx.o \
	$(GAME_SERVER_OBJ_DIR)/basetempentity.o \
	$(GAME_SERVER_OBJ_DIR)/event_tempentity_tester.o \
	$(GAME_SERVER_OBJ_DIR)/movie_explosion.o \
	$(GAME_SERVER_OBJ_DIR)/particle_fire.o \
	$(GAME_SERVER_OBJ_DIR)/particle_smokegrenade.o \
	$(GAME_SERVER_OBJ_DIR)/plasma.o \
	$(GAME_SERVER_OBJ_DIR)/smoke_trail.o \
	$(GAME_SERVER_OBJ_DIR)/smokestack.o \
	$(GAME_SERVER_OBJ_DIR)/steamjet.o \
	$(GAME_SERVER_OBJ_DIR)/te.o \
	$(GAME_SERVER_OBJ_DIR)/te_armorricochet.o \
	$(GAME_SERVER_OBJ_DIR)/te_basebeam.o \
	$(GAME_SERVER_OBJ_DIR)/te_beamentpoint.o \
	$(GAME_SERVER_OBJ_DIR)/te_beaments.o \
	$(GAME_SERVER_OBJ_DIR)/te_beamfollow.o \
	$(GAME_SERVER_OBJ_DIR)/te_beamlaser.o \
	$(GAME_SERVER_OBJ_DIR)/te_beampoints.o \
	$(GAME_SERVER_OBJ_DIR)/te_beamring.o \
	$(GAME_SERVER_OBJ_DIR)/te_beamringpoint.o \
	$(GAME_SERVER_OBJ_DIR)/te_beamspline.o \
	$(GAME_SERVER_OBJ_DIR)/te_bloodsprite.o \
	$(GAME_SERVER_OBJ_DIR)/te_bloodstream.o \
	$(GAME_SERVER_OBJ_DIR)/te_breakmodel.o \
	$(GAME_SERVER_OBJ_DIR)/te_bspdecal.o \
	$(GAME_SERVER_OBJ_DIR)/te_bubbles.o \
	$(GAME_SERVER_OBJ_DIR)/te_bubbletrail.o \
	$(GAME_SERVER_OBJ_DIR)/te_clientprojectile.o \
	$(GAME_SERVER_OBJ_DIR)/te_decal.o \
	$(GAME_SERVER_OBJ_DIR)/te_dynamiclight.o \
	$(GAME_SERVER_OBJ_DIR)/te_effect_dispatch.o \
	$(GAME_SERVER_OBJ_DIR)/te_energysplash.o \
	$(GAME_SERVER_OBJ_DIR)/te_explosion.o \
	$(GAME_SERVER_OBJ_DIR)/te_fizz.o \
	$(GAME_SERVER_OBJ_DIR)/te_footprintdecal.o \
	$(GAME_SERVER_OBJ_DIR)/te_glassshatter.o \
	$(GAME_SERVER_OBJ_DIR)/te_glowsprite.o \
	$(GAME_SERVER_OBJ_DIR)/te_impact.o \
	$(GAME_SERVER_OBJ_DIR)/te_killplayerattachments.o \
	$(GAME_SERVER_OBJ_DIR)/te_largefunnel.o \
	$(GAME_SERVER_OBJ_DIR)/te_muzzleflash.o \
	$(GAME_SERVER_OBJ_DIR)/te_particlesystem.o \
	$(GAME_SERVER_OBJ_DIR)/te_physicsprop.o \
	$(GAME_SERVER_OBJ_DIR)/te_playerdecal.o \
	$(GAME_SERVER_OBJ_DIR)/te_projecteddecal.o \
	$(GAME_SERVER_OBJ_DIR)/te_showline.o \
	$(GAME_SERVER_OBJ_DIR)/te_smoke.o \
	$(GAME_SERVER_OBJ_DIR)/te_sparks.o \
	$(GAME_SERVER_OBJ_DIR)/te_sprite.o \
	$(GAME_SERVER_OBJ_DIR)/te_spritespray.o \
	$(GAME_SERVER_OBJ_DIR)/te_worlddecal.o \
	$(GAME_SERVER_OBJ_DIR)/basebludgeonweapon.o \
	$(GAME_SERVER_OBJ_DIR)/weapon_cubemap.o \
	$(GAME_SERVER_OBJ_DIR)/playerinfomanager.o \
	$(GAME_SERVER_OBJ_DIR)/entity_tools_server.o \
	$(GAME_SERVER_OBJ_DIR)/toolframework_server.o \


GAME_SERVER___COMMON_OBJS= \
	$(GAME_SERVER___COMMON_OBJ_DIR)/randoverride.o \


GAME_SERVER___PUBLIC_OBJS= \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/bone_setup.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/collisionutils.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/dt_send.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/dt_utlvector_common.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/dt_utlvector_send.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/editor_sendcommand.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/filesystem_helpers.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/interpolatortypes.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/map_utils.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/networkvar.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/registry.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/rope_physics.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/scratchpad3d.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/ScratchPadUtils.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/server_class.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/simple_physics.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/SoundParametersInternal.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/stringregistry.o \
	$(GAME_SERVER___PUBLIC_OBJ_DIR)/studio.o \


GAME_SERVER___PUBLIC_KEYFRAME_OBJS= \
	$(GAME_SERVER___PUBLIC_KEYFRAME_OBJ_DIR)/keyframe.o \


GAME_SERVER___PUBLIC_TIER0_OBJS= \
	$(GAME_SERVER___PUBLIC_TIER0_OBJ_DIR)/memoverride.o \


GAME_SERVER__SHARED_OBJS= \
	$(GAME_SERVER__SHARED_OBJ_DIR)/achievement_saverestore.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/achievementmgr.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/achievements_hlx.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/activitylist.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/ammodef.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/animation.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/base_playeranimstate.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/baseachievement.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/basecombatcharacter_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/basecombatweapon_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/baseentity_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/basegrenade_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/baseparticleentity.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/baseplayer_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/baseviewmodel_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/beam_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/collisionproperty.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/death_pose.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/debugoverlay_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/decals.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/effect_dispatch_data.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/ehandle.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/entitylist_base.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/EntityParticleTrail_Shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/env_detail_controller.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/env_wind_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/eventlist.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/func_ladder.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/gamemovement.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/gamerules.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/gamerules_register.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/GameStats.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/gamestringpool.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/gamevars_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/hintmessage.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/hintsystem.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/igamesystem.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/interval.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/mapentities_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/ModelSoundsCache.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/movevars_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/mp_shareddefs.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/multiplay_gamerules.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/obstacle_pushaway.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/particle_parse.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/particlesystemquery.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/physics_main_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/physics_saverestore.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/physics_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/point_bonusmaps_accessor.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/point_posecontroller.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/precache_register.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/predictableid.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/predicted_viewmodel.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/props_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/ragdoll_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/rope_helpers.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/saverestore.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/SceneCache.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/sceneentity_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/sequence_Transitioner.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/sheetsimulator.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/simtimer.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/singleplay_gamerules.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/SoundEmitterSystem.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/soundenvelope.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/Sprite.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/studio_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/takedamageinfo.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/teamplay_gamerules.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/test_ehandle.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/usercmd.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/util_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/vehicle_viewblend_shared.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/voice_gamemgr.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/weapon_parse.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/weapon_proficiency.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/SpriteTrail.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/usermessages.o \
	$(GAME_SERVER__SHARED_OBJ_DIR)/script_intro_shared.o \


GAME_SERVER__SHARED_HL2_OBJS= \
	$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/survival_gamerules.o \
	$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/basehlcombatweapon_shared.o \
	$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/env_headcrabcanister_shared.o \
	$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/hl2_gamerules.o \
	$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/hl2_usermessages.o \
	$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/hl_gamemovement.o \


GAME_SERVER__SHARED_HL2MP_OBJS= \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_bat.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_bazooka.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_bigshotgun.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_carebearstare.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_crowbar.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_flower.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_flowerlauncher.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_frag.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_grenade.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_hl2mpbase.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_hl2mpbasebasebludgeon.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_hl2mpbasehlmpcombatweapon.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_hl2mpbase_machinegun.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_mine.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_pushball.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_revolver.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_rpg.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_tranquilizer.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/weapon_uzi.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/hl2mp_gamerules.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/hl2mp_player_shared.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/hl2mp_playeranimstate.o \
	$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/hl2mp_weapon_parse.o \


GAME_SERVER__SHARED_MULTIPLAYER_OBJS= \
	$(GAME_SERVER__SHARED_MULTIPLAYER_OBJ_DIR)/multiplayer_animstate.o \


GAME_SERVER_HL2_OBJS= \
	$(GAME_SERVER_HL2_OBJ_DIR)/Func_Monitor.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_armor.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_fastzombie.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_pedobear.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/te_gaussexplosion.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_allymanager.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_behavior_actbusy.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_behavior_functank.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_behavior_holster.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_behavior_police.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_goal_police.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ai_spotlight.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/antlion_dust.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/antlion_maker.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/ar2_explosion.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/basehlcombatweapon.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/cbasehelicopter.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/cbasespriteprojectile.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/citadel_effects.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/combine_mine.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/env_alyxemp.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/env_headcrabcanister.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/env_speaker.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/env_starfield.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/func_recharge.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/func_tank.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/grenade_ar2.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/grenade_bugbait.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/grenade_frag.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/hl2_ai_network.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/hl2_eventlog.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/hl2_player.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/hl2_playerlocaldata.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/hl2_triggers.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/hl_playermove.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/info_teleporter_countdown.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_ammo.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_battery.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_dynamic_resupply.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_healthkit.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_itemcrate.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/item_suit.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/look_door.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/monster_dummy.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_alyx.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_antlion.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_antlionguard.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_apcdriver.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_attackchopper.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_barnacle.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_barney.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_basescanner.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_BaseZombie.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_breen.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_bullseye.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_citizen17.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_combine.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_combinecamera.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_combinedropship.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_combinegunship.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_combines.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_cranedriver.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_crow.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_dog.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_eli.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_enemyfinder.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_fisherman.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_gman.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_headcrab.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_ichthyosaur.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_kleiner.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_launcher.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_manhack.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_metropolice.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_monk.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_mossman.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_playercompanion.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_PoisonZombie.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_rollermine.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_scanner.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_strider.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_turret_ceiling.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_turret_floor.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_turret_ground.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_vortigaunt_episodic.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/npc_zombie.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/point_apc_controller.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/prop_combine_ball.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/prop_thumper.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/proto_sniper.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/rotorwash.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/script_intro.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/vehicle_airboat.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/vehicle_crane.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/vehicle_prisoner_pod.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/vehicle_viewcontroller.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/grenade_beam.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/grenade_homer.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/grenade_pathfollower.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/vehicle_apc.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/weapon_cguard.o \
	$(GAME_SERVER_HL2_OBJ_DIR)/weapon_flaregun.o \


GAME_SERVER_HL2MP_OBJS= \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/grenade_boing.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/grenade_satchel.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/grenade_tripmine.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/npc_mine.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/te_hl2mp_shotgun_shot.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/hl2mp_bot_temp.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/hl2mp_client.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/hl2mp_cvars.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/hl2mp_gameinterface.o \
	$(GAME_SERVER_HL2MP_OBJ_DIR)/hl2mp_player.o \




all: dirs $(NAME)_$(ARCH).$(SHLIBEXT)

dirs:
	-mkdir -p $(GAME_SERVER_OBJ_DIR)
	-mkdir -p $(GAME_SERVER___COMMON_OBJ_DIR)
	-mkdir -p $(GAME_SERVER___PUBLIC_OBJ_DIR)
	-mkdir -p $(GAME_SERVER___PUBLIC_KEYFRAME_OBJ_DIR)
	-mkdir -p $(GAME_SERVER___PUBLIC_TIER0_OBJ_DIR)
	-mkdir -p $(GAME_SERVER__SHARED_OBJ_DIR)
	-mkdir -p $(GAME_SERVER__SHARED_HL2_OBJ_DIR)
	-mkdir -p $(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)
	-mkdir -p $(GAME_SERVER__SHARED_MULTIPLAYER_OBJ_DIR)
	-mkdir -p $(GAME_SERVER_HL2_OBJ_DIR)
	-mkdir -p $(GAME_SERVER_HL2MP_OBJ_DIR)




$(NAME)_$(ARCH).$(SHLIBEXT): $(GAME_SERVER_OBJS) $(GAME_SERVER___COMMON_OBJS) $(GAME_SERVER___PUBLIC_OBJS) $(GAME_SERVER___PUBLIC_KEYFRAME_OBJS) $(GAME_SERVER___PUBLIC_TIER0_OBJS) $(GAME_SERVER__SHARED_OBJS) $(GAME_SERVER__SHARED_HL2_OBJS) $(GAME_SERVER__SHARED_HL2MP_OBJS) $(GAME_SERVER__SHARED_MULTIPLAYER_OBJS) $(GAME_SERVER_HL2_OBJS) $(GAME_SERVER_HL2MP_OBJS) 
	$(CLINK) $(SHLIBLDFLAGS) $(DEBUG) -o $(BUILD_DIR)/$@ $(GAME_SERVER_OBJS) $(GAME_SERVER___COMMON_OBJS) $(GAME_SERVER___PUBLIC_OBJS) $(GAME_SERVER___PUBLIC_KEYFRAME_OBJS) $(GAME_SERVER___PUBLIC_TIER0_OBJS) $(GAME_SERVER__SHARED_OBJS) $(GAME_SERVER__SHARED_HL2_OBJS) $(GAME_SERVER__SHARED_HL2MP_OBJS) $(GAME_SERVER__SHARED_MULTIPLAYER_OBJS) $(GAME_SERVER_HL2_OBJS) $(GAME_SERVER_HL2MP_OBJS) $(LDFLAGS) $(CPP_LIB)

$(GAME_SERVER_OBJ_DIR)/%.o: $(GAME_SERVER_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER___COMMON_OBJ_DIR)/%.o: $(GAME_SERVER___COMMON_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER___PUBLIC_OBJ_DIR)/%.o: $(GAME_SERVER___PUBLIC_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER___PUBLIC_KEYFRAME_OBJ_DIR)/%.o: $(GAME_SERVER___PUBLIC_KEYFRAME_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER___PUBLIC_TIER0_OBJ_DIR)/%.o: $(GAME_SERVER___PUBLIC_TIER0_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER__SHARED_OBJ_DIR)/%.o: $(GAME_SERVER__SHARED_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER__SHARED_HL2_OBJ_DIR)/%.o: $(GAME_SERVER__SHARED_HL2_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER__SHARED_HL2MP_OBJ_DIR)/%.o: $(GAME_SERVER__SHARED_HL2MP_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER__SHARED_MULTIPLAYER_OBJ_DIR)/%.o: $(GAME_SERVER__SHARED_MULTIPLAYER_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER_HL2_OBJ_DIR)/%.o: $(GAME_SERVER_HL2_SRC_DIR)/%.cpp
	$(DO_CC)

$(GAME_SERVER_HL2MP_OBJ_DIR)/%.o: $(GAME_SERVER_HL2MP_SRC_DIR)/%.cpp
	$(DO_CC)

